USE [Paste Configuration Hub Database Name Here]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CFGHub_SystemComponent](
	[ID] [uniqueidentifier] NOT NULL,
	[Status] [varchar](1) NOT NULL,
	[Name] [varchar](255) NOT NULL,
	[Version] [varchar](255) NULL,
	[Description] [text] NULL,
 CONSTRAINT [PK_CFGHub_SystemComponent] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO