//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFG.Hub
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFGHub_SystemComponent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CFGHub_SystemComponent()
        {
            this.CFGHub_ConfigAtom = new HashSet<CFGHub_ConfigAtom>();
        }
    
        public System.Guid ID { get; set; }
        public string Status { get; set; }
        public string Name { get; set; }
        public string Version { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFGHub_ConfigAtom> CFGHub_ConfigAtom { get; set; }
    }
}
