//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFG.Hub
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFGHub_ConfigAtom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CFGHub_ConfigAtom()
        {
            this.Children = new HashSet<CFGHub_ConfigAtom>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid ComponentID { get; set; }
        public Nullable<System.Guid> ParentID { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
    
        public virtual CFGHub_SystemComponent CFGHub_SystemComponent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CFGHub_ConfigAtom> Children { get; set; }
        public virtual CFGHub_ConfigAtom Parent { get; set; }
    }
}
