//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFG.Hub
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConfigHubEFEntities : DbContext
    {
        public ConfigHubEFEntities()
            : base("name=ConfigHubEFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CFGHub_ConfigAtom> CFGHub_ConfigAtom { get; set; }
        public virtual DbSet<CFGHub_SystemComponent> CFGHub_SystemComponent { get; set; }
    }
}
